### ISSUE TITLE
how to handle nested objects

### ISSUE THREAD

**Issue by mderazon** [wdavidw/node-csv-stringify#16]
Hi, 
Thanks for this nice module, helps me stream export large JSON data sets to csv.

Was wondering what't your take on nested object i.e.
``` json
{ 
  "name": "Michael",
  "address": {
    "street": "baker st",
    "city": "bla bla"
  }
}
```

How would you recommend exporting this document to csv ?

**Comment by wdavidw** [comment]
As far as I can tell, there isn't a perfect answer for nested object. CSV isn't the most appropriate format for this. I'll rather use one json record per line.

Now, the answer can be a little more detailed. Usually, the conclusions are the same when mapping your json object into an sql schema which is also column based.

Considering your example, you could simply flatten your object into something like:

```json
{
  "name": "Michael",
  "address.street": "baker st",
  "address.city": "sf"
}
```
and you'll be just fine. Problem start when you have an array. Consider this:

```json
{ 
  "name": "Michael",
  "addresses": [{
    "street": "baker st",
    "city": "sf"
  },{
    "street": "rue du paradis",
    "city": "paris"
  }]
}
```

Here, you only solution might be to introduce sub-delimiter for example:


```json
Michael;baker st.sf,rue du paradis.paris
```
Here, ";" seperates columns, "," separates elements of an array, "." separates values of an object inside an array. Not so good and this package doesnt supports it.

**Comment by mderazon** [comment]
some good points, thanks!
