### ISSUE TITLE
Stringify with empty columns

### ISSUE THREAD

**Issue by ilanbiala** [wdavidw/node-csv-stringify#20]
If I have columns that act as padding, and the number of columns is greater than 1, it seems that 1 column is ignored and some of the data is shifted around. Ideally, I would like to be able to pass in `['', '', '', 'abc', '', '', '']` and have a CSV with 7 columns and only 1 filled in.

**Comment by wdavidw** [comment]
could you provide me with a little example of what you expect

**Comment by ilanbiala** [comment]
`['123', '', '', 'abc', '', '', '456']` should produce `"123", "", "", "abc", "", "", "456"` and when previewed in Google Sheets should have 7 cells.

**Comment by wdavidw** [comment]
and what do u get instead?

**Comment by wdavidw** [comment]
i wrote a small test and it seems to be ok. make sure u're using the "quotedEmpty" option.

```coffee
stringify [['123', '', '', 'abc', '', '', '456']], quoted: true, quotedEmpty: true, eof: false, (err, data) ->
  data.should.eql '"123","","","abc","","","456"'
```
