### ISSUE TITLE
Documentation unclear for CSV Stringifier options:  lineBreaks and rowDelimiter 

### ISSUE THREAD

**Issue by cookch10** [wdavidw/node-csv-stringify#22]
On the [documentation page](http://csv.adaltas.com/stringify/), the following options have the same description:

-  `lineBreaks`:  String used to delimit record rows or a special value; special values are 'auto', 'unix', 'mac', 'windows', 'unicode'; defaults to 'auto' (discovered in source or 'unix' if no source is specified).

-  `rowDelimiter`:  String used to delimit record rows or a special value; special values are 'auto', 'unix', 'mac', 'windows', 'unicode'; defaults to 'auto' (discovered in source or 'unix' if no source is specified).

Do these options serve different purposes?  If so, could you please clarify what each option does?

**Comment by Drarok** [comment]
I've just had to dig into the source to work out what what going on with my code. As far as I can see, the `lineBreaks` option is never used. `rowDelimiter` is automatically appended to every line, and likely the option you want.

**Comment by cookch10** [comment]
Thanks @Drarok.  I came to the same conclusion as I've had to dig into the codebase to work out some other issues.  Hoping the author will update the documentation at some point.

**Comment by wdavidw** [comment]
ok, i can update documentation and source code. since we are discussing this, i've never been happy with "rowDelimiter" for lines and "delimiter" for columns. Isnt line_breaks better or do u have any other suggestions

**Comment by Drarok** [comment]
I think `lineBreaks` would have been great, but it doesn't do anything? :)

**Comment by wdavidw** [comment]
i could update the code to accept both and eventually print a warning is the deprecated one is used. Also, i'm thinking to use underscore variable instead of camelCase

**Comment by Drarok** [comment]
Why's that? Everything else seems to be camelCase. I could get behind a deprecated notice.

**Comment by wdavidw** [comment]
i wasnt clear, i meant to convert all options as undescore, that would be for a new major version release and camelCase options would be converted to underscore with a warning

**Comment by Drarok** [comment]
That seems weird to me. Most everything [uses][express] [camelCase][request], including [core node itself][node].

[express]: http://expressjs.com/4x/api.html#req.baseUrl
[request]: https://github.com/request/request#requestoptions-callback
[node]: https://nodejs.org/api/stream.html#stream_new_stream_readable_options

**Comment by cookch10** [comment]
I agree with @Drarok and suggest using (lower) camelCase since it is a fairly standard node convention.  I think `rowDelimiter` is acceptable.  For columns, I am actually OK with `delimiter`, however something more descriptive like `fieldDelimiter` would be appropriate.

**Comment by wdavidw** [comment]
thanks for your inputs, i'll keep your comments in mind for futur refactoring
