### ISSUE TITLE
Using nested columns

### ISSUE THREAD

**Issue by nielsdebruin** [wdavidw/node-csv-stringify#23]
I ran into the follow issue:

1. I have a data Model (Mongoose) in this case.
2. My Model has some nested properties.
3. Csv stringify columns do not seems to be able to find properties deeper than level 1. 
4. I would like to be able to access my nested models and map then to csv columns without the need to first mapping them to level 1 properties on the same model.

```
// Example Model
var model = {
  'nameOnModel' : 'myName',
  'address': {
    'street' : 'LongRoad'
  }
}

var columns = {
  'nameOnModel' : 'nameOfHeader', // This works fine
  'address.street' : 'street' // This does not
}
var stringifier = csv.stringify({columns: columns, header: true})

stringifier.write(model)
stringifier.pipe(process.stdout)

// Output
nameOfHeader, street
myName, 
```

**Comment by wdavidw** [comment]
this make sense but i wont have time to implement it

**Comment by keatz55** [comment]
+1

**Comment by wdavidw** [comment]
i will accept pull requests implementing this feature

**Comment by jdnichollsc** [comment]
+1

**Comment by tomyam1** [comment]
An easy solution is to just flatten the objects before passing them to csv-stringify, e.g. using [flat](https://github.com/hughsk/flat).
