### ISSUE TITLE
Stringify behavior for boolean field

### ISSUE THREAD

**Issue by truongduy134** [wdavidw/node-csv-stringify#27]
Currently, when stringifying a boolean field, the output value is either 1 (for true) and empty string (for false) (https://github.com/wdavidw/node-csv-stringify/blob/master/lib/index.js#L245) . Would it be nicer if we print a string "true" (for true), and "false" (for false) in the result CSV string? Or can we have an option to customize this behavior?

**Comment by wdavidw** [comment]
The option is the only way to go since "true" and "false" depend on the language. Send a pull request if still interested.

**Comment by truongduy134** [comment]
@wdavidw : Will work on this and submit a pull request soon

**Comment by wdavidw** [comment]
you can look at issue #33 introducing custom boolean formatter
