### ISSUE TITLE
Sync version

### ISSUE THREAD

**Issue by Vanuan** [wdavidw/node-csv-stringify#30]
Is it hard to provide synchronous version of that?

**Comment by wdavidw** [comment]
technically no, it's more about how to enrich the api without confusing the end user.

**Comment by Vanuan** [comment]
This?
```
output = stringifySync(input);
output.should.eql('1,2,3,4\na,b,c,d');
```

**Comment by Vanuan** [comment]
Well, meanwhile I solved my problem using streaming version, so I think it can be closed.

**Comment by wdavidw** [comment]
to have it work, you'll need

```
stringifySync = require('csv-stringify-sync');
output = stringifySync(input);
output.should.eql('1,2,3,4\na,b,c,d');
```

which i think isnt nice, i'll rather have:

```
stringify = require('csv-stringify');
output = stringify.sync(input);
output.should.eql('1,2,3,4\na,b,c,d');
```

which would be quite easy to implement but confusing to explain

**Comment by Vanuan** [comment]
Yeap, that's why one-function modules are not very extensible.
