### ISSUE TITLE
csv-stringify@1.0.2- Quoted strings get extra double quotes."1" -> """1"""

### ISSUE THREAD

**Issue by divyavanmahajan** [wdavidw/node-csv-stringify#37]
Extra double quotes are generated when the string is already enclosed in double quotes.
So `"1"` is output as `"""1"""`.

```javascript
input = [ [ '"1"', '2', '3', '4' ], [ 'a', 'b', 'c', 'd' ] ];
stringify(input,function(output)
{
        console.log(output);
});
```
I expected the output to be 
```
"1",2,3,4
a,b,c,d
```
Actual result was:
```
"""1""",2,3,4
a,b,c,d
```

**Comment by wdavidw** [comment]
this seems normal to me, you're asking to stringify `"1"` and not `1`, the package is only doing its job.

**Comment by jcdickman** [comment]
So if I am trying to create a CSV that has a quote string in it, like 

```
my test 1, my_test_1, "my test 1"
my test 2, my_test_2, "my test 2"
```

is that even possible with this module? or is that simply not a "job" this module can do?

**Comment by jcdickman** [comment]
I found a workaround... If you want to accomplish what I have above as an output, add the quote option with something "safe" that is not a ", like for example:

`const options = {
                header: true,
                quote: '$*%^&*$'
            };`

That allowed my output to be:

`my test 1, my_test_1, "my test 1"
my test 2, my_test_2, "my test 2"`

Perhaps that will help someone.

**Comment by wdavidw** [comment]
@jcdickman  please dont hijack a thread and open a new issue if you need to.

**Comment by jcdickman** [comment]
Sorry if I wasn't more clear, I commented here because I was having the exact same issue as the OP. My expected output was
```
my test 1, my_test_1, "my test 1"
my test 2, my_test_2, "my test 2"
```
instead I got 
`my test 1, my_test_1, """my test 1"""
my test 2, my_test_2, """my test 2"""`

If someone else has the exact same issue, and lands here, they will now see the workaround I did. I you would prefer that be in a new thread I apologize, not intending to hijack anything. Thanks.

**Comment by wdavidw** [comment]
what is your input? I guess ` "my test 1"`. In such case, since the default quoting value is double quotes `"`, then what you are observing is expected. Providing an alternative quote value and possibly an unreachable one like you did, is a valid approach.

**Comment by jcdickman** [comment]
Yes, that was the input.
