### ISSUE TITLE
\t for delimeter produces \ and t instead of real tabs

### ISSUE THREAD

**Issue by jcollum** [wdavidw/node-csv-stringify#40]
```
stringify results[0], {delimiter: '\t', header: true}, (err, output) -> 
```

Expected things like: 

```
1   2   3
```

But I got:     

```
1\t2\t3
```

Using `\\t` did not fix it. The actual fix was to replace the `\t` directly: 

```
output.replace(/\\t/, '\t')
```

**Comment by jcollum** [comment]
This does work together: 

    stringify results[0], {delimiter: '\u0009', header: true}, (err, output) -> 

Add that to the docs?

**Comment by wdavidw** [comment]
i dont know how u get this result, both lines bellow print true inside a console:

```
expect = 'a\tb\tc\nd\te\tf\n'
stringify [['a','b','c'],['d','e','f']], delimiter: '\t', (err, data) -> console.log data is expect
stringify [['a','b','c'],['d','e','f']], delimiter: '\u0009', (err, data) -> console.log data is expect
```

**Comment by wdavidw** [comment]
I tried again and it seems like it works just fine. closing
