### ISSUE TITLE
does not implement quote disablement

### ISSUE THREAD

**Issue by davidgwking** [wdavidw/node-csv-stringify#41]
Hello,

Is there a particular reason why this library doesn't allow one to disable quoting and therefore escape the delimiter and newline characters?

If not, would you be willing to accept a PR? 

Looking at a couple of other reputable encoders for node, this feature does not seem to be common. In fact, I've not found one that allows me to disable quotes all together.

**Comment by wdavidw** [comment]
could u give me an example?

**Comment by davidgwking** [comment]
Thanks for the quick reply! 

My premise is that I have some requirements which dictate that my encoded csv shall have the following characteristics:
  * tab delimited
  * backslash escaped
  * unix line endings
  * cells shall not be quoted

Assuming the following input...

```js
[
  ['field', 'needs escaped', 'also needs escaped', 'numbers', 'null'],
  ['my field', 'this\tis\ta\ttest', 'abc\n123', 12.35, null]
]
```

In this scenario, I'd be expected to produce the following output...

```tsv
field\tneeds escaped\talso needs escaped\tnumbers\tnull\n
my field\tthis\\\tis\\\ta\\\ttest\tabc\\\n123\t12.35\t\n
```

**Comment by wdavidw** [comment]
I took a quick look at the source code, seems like you would have to line 199 to something similar to `shouldQuote = ...` to `shouldQuote = not options.neverQuote or ...`. However, it seems like you could simply use the [transform](http://csv.adaltas.com/stringify/) projet and implement your own stringifying logic.

**Comment by davidgwking** [comment]
Hi @wdavidw 

Thanks for the tips. I ended up trivially implementing my own encoder that accomplishes what I need.

Closing this one out.
