### ISSUE TITLE
Does not preserve data types

### ISSUE THREAD

**Issue by BAM5** [wdavidw/node-csv-stringify#45]
When writing {zip: "01234"} in the csv file it turns into
Zip
1234

**Comment by wdavidw** [comment]
Not nice, not expected

**Comment by BAM5** [comment]
Ugggh, at first I thought it was nedb doing this. Tested it, it wasn't. Assumed it was csv-stringify, my bad my bad, it wasn't. After going through your source for a while and tracking the data through it with console logs, I found that it when it went to stream.Transform.prototype.write, it appeared to be fine there as well. SO I decided I'd look at the CSV in a text editor instead of open GOD DAMN office. And there were the leading 0s in my zips.... Damn you open office, you wasted my life and made me look a fool!

**Comment by wdavidw** [comment]
:)
