### ISSUE TITLE
Is it memory leak?

### ISSUE THREAD

**Issue by Pixmap** [wdavidw/node-csv-stringify#46]
Hi!
I have an example bellow. When /test request has arrived application memory usage fast grows and finally app crashes with out of memory error. I tried to do small amount of iteration to try to release memory through stringifier.end(), but after I've called /stop memory is not released. My question is it a real leak, or I just forgot something to do? I doubt because in description said that "It was first released in 2010 and is used against big data sets by a large community". But I did not find anything useful in the documentation.

I've tested on Win x64, node 4.4.7 and 4.2.2, csv 1.1.0
```
var express = require('express');
var app = express();
var http = require("http");
var csv = require('csv');
var server = http.createServer(app);
var stringifier = csv.stringify();

server.listen(1111);

app.get('/test', function (request, response) {
  for(var i = 0; i < 10000000; ++i) {
    stringifier.write("Hello world");
  }
  response.end('ok');
});

app.get('/stop', function (request, response) {
    stringifier.end();
    response.end('ok stop');
});
```

**Comment by wdavidw** [comment]
not sure what you expect. you're writing intensively data to an object without controling its flow or consuming it. read the [csv](http://csv.adaltas.com) and [stream](http://nodejs.org/api/stream.html) documentation and look at tests and examples.

**Comment by Pixmap** [comment]
Yes, it was my mistake.. I didn't read results from the stream.
I added this code and it helps.
```
stringifier.on('readable', function(){
  while(row = stringifier.read()){
  }
});
```
