### ISSUE TITLE
Synchronous stringify

### ISSUE THREAD

**Issue by Sincap80** [wdavidw/node-csv-stringify#49]
Hello mate,

thanks for the nice parser, but it would be nice if you would document the synchronous version of your stringifiy (csv-stringify/lib/sync)

Best Regards

**Comment by M320Trololol** [comment]
Why ask for documentation? Just look at the code, it's probably self-explanatory...

**Comment by wdavidw** [comment]
If you feel that to doc could be more accurate or rich, please propose a pull request [on the project website](https://github.com/wdavidw/node-csv-docs)
