### ISSUE TITLE
using pipe api: delimiter option not working for array objects

### ISSUE THREAD

**Issue by gbbauto** [wdavidw/node-csv-stringify#5]
I am having a bit of trouble.

when the callback of the transformer returns a multiple line output like
[ [ '1', '2', '3', '4' ], [ 'a', 'b', 'c', 'd' ] ]

(the transformer took a line from the parser and created 2 lines)

and i want to use a delimiter option other than comma:

var stringifier = require('csv-stringify')({delimiter: '\t'});

The pipe process does not seem to follow the delimiter option set, it always uses comma.

rs.pipe(parser).pipe(transformer).pipe(stringifier).pipe(process.stdout);

I noticed that in the callback api the array is iterated over, but in the pipe not sure where it iterates.

**Comment by wdavidw** [comment]
Please provide me with a sample or I will have to close the issue.
